name: Build

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '25'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build